services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    env_file:
      - .env

  order-worker:
    build:
      context: ./order-worker
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "3002:3000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./order-worker:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    env_file:
      - .env

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "3001:3000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    env_file:
      - .env

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_worker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
