export const NOTIFICATION_OPTIONS = 'NOTIFICATION_OPTIONS';
export const NOTIFICATION_FEATURE_OPTIONS = 'NOTIFICATION_FEATURE_OPTIONS';
export const NOTIFICATION_FEATURE_REGISTRY = 'NOTIFICATION_FEATURE_REGISTRY';
